apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddivyanshcephfspvcoutputexp
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti

