apiVersion: v1
kind: Pod
metadata:
  name: saqib-simple-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: saqib-container
    image: ubuntu
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
  #   volumeMounts:
  #   - mountPath: /saqibcephfspvc
  #     name: saqibcephfspvc
  # volumes:
  #   - name: saqibcephfspvc
  #     persistentVolumeClaim:
  #       claimName: saqibcephfspvc